# Generated by Django 5.0.4 on 2024-04-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_purchase_price_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, default='https://via.placeholder.com/300x300.png?text=Product+Image', max_length=200, null=True),
        ),
    ]
