# Generated by Django 5.0.4 on 2024-04-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, default='https://via.placeholder.com/300x300.png?text=<django.db.models.fields.CharField>', max_length=200, null=True),
        ),
    ]
